version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: centos
    group: centos

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: centos